### ISSUE TITLE
Rename this extension.

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbpuller#2]
This extension was named after the INTERACT button labels of the inferentialthinking.com textbook, but "interact" doesn't accurately convey what it does. There's also "nteract" in the notebook-verse namespace.

Suggestions:

nbimport
nbfetch
nbpull
nbclone

**Comment by ryanlovett** [comment]
Yuvi said:

> Did this happen? What name was decided on? I'm personally partial to 'nbgitpull' since that's very accurate, and if not that than 'nbpull'. nbimport already exists, hooking up notebooks into python's import machinery.

This extension can pull arbitrary URLs too so maybe nbgitpull is too narrow.

Whatever the route name should also be modified accordingly.

**Comment by yuvipanda** [comment]
ah, ok! nbpuller?

**Comment by ryanlovett** [comment]
Sounds good to me.

@SaladRaider @SamLau95, thoughts?

**Comment by SaladRaider** [comment]
nbpuller sounds find.
