### ISSUE TITLE
Incorrect version when re-pulling files

### ISSUE THREAD

**Issue by gunjanbaid** [data-8/nbpuller#31]
After an assignment has been updated, interact links redirect to an older version of the assignment, even after the assignment file is renamed/deleted on datahub. Is there a way to pull the most recent assignment file with the interact link? Seems like a git issue that I was able to fix using git commands in the terminal, but wanted to know if there was an easier way to go about this. Thanks!

**Comment by SaladRaider** [comment]
nbinteract should be pulling in the latest version, especially after renaming/deleting the file on the user's notebook tree. What do the logs say after it pulls in and redirects to the older version of the file?

**Comment by gunjanbaid** [comment]
Attached is a screenshot of what shows up after I re-click the interact link after renaming/deleting previous file. 

<img width="1224" alt="screen shot 2017-03-13 at 12 07 00 am" src="https://cloud.githubusercontent.com/assets/8205702/23844709/39c74ca0-0781-11e7-8935-ecf76e5ad214.png">

Here's a Piazza post from Data 8 that mentions the same problem: [https://piazza.com/class/ixxlkoprjq27g5?cid=727](https://piazza.com/class/ixxlkoprjq27g5?cid=727)

**Comment by SaladRaider** [comment]
Hmm... I'm not able to recreate the error for some reason. Here is what I am doing to try to recreate it, let me know if I'm missing something:

I first pull in lab6 with this link: `http://datahub.berkeley.edu/user-redirect/interact?repo=mcb-88-connector&path=notebooks/Lab6.ipynb`

I then opened a new terminal and did a 
`git checkout HEAD~2`
resulting in `cbd6abc Merge pull request #15 from akmorrow13/master` being the latest commit.

I then edited `Lab6.ipynb` by adding random text to the first header and then saving it.

I renamed `Lab6.ipynb` to `Lab6_backup.ipynb`.

I then hit the same interact link again, and found that the new `Lab6.ipynb` gave me a fresh notebook to start from.

**Comment by gunjanbaid** [comment]
Hi @SaladRaider, you can ignore the Piazza post link earlier, I realized that does not fully describes the current issue. The problem is happening for instructors in particular, and I think it may be because they already have a version of the notebook on DataHub before they pull the first time. 

So the example workflow:
1. Create notebook locally, push changes to GitHub as you work
2. Upload the notebook to DataHub to test
3. Original person or someone else may push more changes to GitHub
4. Test interact link, which either doesn't pull anything and is stuck on the page I showed an image of above, or seems to pull content, but just redirects to the version on DataHub, instead of pulling the updated GitHub version. 

Here are images of two posts that connector course instructors have made regarding the issue. 

![image](https://cloud.githubusercontent.com/assets/8205702/23982402/7374d22e-09ca-11e7-9f50-1a2381a5c008.png)

![image](https://cloud.githubusercontent.com/assets/8205702/23982409/7f2c9c00-09ca-11e7-8c35-ba73b82cf908.png)

**Comment by SaladRaider** [comment]
@gunjanbaid 
It seems like the instructors still have a local version of the lab/homework on their notebooks, is that right? But their version is an older version of the upstream one? I will try to test and see if I can recreate this problem.

**Comment by gunjanbaid** [comment]
Yes, I believe that was the issue. I will be meeting with both instructors who had problems with the links today so I can give you some more details after I talk to them in person.

**Comment by SaladRaider** [comment]
@gunjanbaid 
Ok sounds good.

I tried another test so far:
I first pull in lab6 with this link: http://datahub.berkeley.edu/user-redirect/interact?repo=mcb-88-connector&path=notebooks/Lab6.ipynb

I then opened a new terminal and did a
git checkout HEAD~2
resulting in cbd6abc Merge pull request #15 from akmorrow13/master being the latest commit.

I then edited Lab6.ipynb by adding random text to the first header and then saving it. This time, I did not rename or delete the file

I hit the interact link again. I opened Lab6.ipynb and did a Ctrl+F and searched for 'You will need to use code to answer this question', which was a new piece of text that was added in after the edit to Lab6.ipynb, and was able to find it. It seems like interact successfully merged in this case.

I will try testing several more scenarios.

**Comment by SaladRaider** [comment]
@gunjanbaid if there are any instructor accounts that are currently still having this issue happen to them now, can you let me know what their accounts are? I will try looking at their notebooks to see what is going on.

**Comment by gunjanbaid** [comment]
@SaladRaider One user was dosullivan and the notebook is geography-88/session4/ASSIGNMENT-2-MAUP.ipynb. 

One thing I want to point out with the above workflows is that you're pulling the notebook in for the first time using the interact link, whereas the instructors first uploaded it by hand, and then pulled a different version in via the interact links. The first version may or may not have been tracked by git, a lot of people do local development and then just upload to datahub to test. 

I was not able to meet with the two people who were having trouble, but hopefully the username/notebook info is useful. I'm also going through the logs for both of them to see if I find anything.

**Comment by SaladRaider** [comment]
@gunjanbaid 
I think I found the issue.

I did a `git status` on dosullivan's notebook, and it said that the branch `is ahead of 'origin/gh-pages' by 36 commits.`. I then checked the github repo and found that the `gh-pages` branch for that repo only has the `README.md` and no other files. However, the `master` branch has all the files.

**Comment by gunjanbaid** [comment]
@SaladRaider The instructor was actually using the following link: `http://datahub.berkeley.edu/user-redirect/interact?repo=geography-88&branch=master&path=session4`

(branch was part of the URL already)

**Comment by SaladRaider** [comment]
@gunjanbaid oops. I see. OK, I'll continue to investigate.

**Comment by SaladRaider** [comment]
@gunjanbaid Ok I did another test:

I opened the session4 notebook and looked for evidence of it being an older version. In this case, I saw that certain import statements were removed in the latest version: https://github.com/data-8/geography-88/commit/66475d02e4de8495e2cb889d7a706853c1bf33fc

The current version the instructor had seemed to be old:
<img width="662" alt="screen shot 2017-03-16 at 11 23 37 pm" src="https://cloud.githubusercontent.com/assets/13090194/24031503/41f83ba6-0aa0-11e7-9a20-15538c6dc801.png">

I then hit the interact link: http://datahub.berkeley.edu/user/dosullivan/interact?repo=geography-88&branch=master&path=session4

It redirected me to the `session4` path. I opened the same notebook, and it looks like the latest changes were merged into the notebook:
<img width="644" alt="screen shot 2017-03-16 at 11 24 49 pm" src="https://cloud.githubusercontent.com/assets/13090194/24031552/76b412e8-0aa0-11e7-936e-210ed49854f5.png">

I will try some more tests. I am guessing that, like you were saying, uploading the file directly to datahub without it being tracked by git, and then pulling may be causing the problems. I will test that scenario next.

**Comment by SaladRaider** [comment]
@gunjanbaid Ok, I was finally able to recreate the error.

It seems that git gets angry when an untracked file with the same name as a file upstream is present during a `git pull`.

Here are some possible ways we might handle this situation:
1. We can have interact rename the file to something like `<file name>.untracked.<unique hash>`
2. Continue to error out but with the write error message. (there is a problem with nbinteract in prod b/c it does not return an error message to the user when something goes wrong. The latest version of nbinteract will, however, tell the user to "Please move or remove [the conflicting file] before you can merge.".)

Here is the error log:
```
[2017-03-17 06:36:08,489] ERROR -- Sent message: {'payload': "exception() missing 1 required positional argument: 'msg'", 'type': 'ERROR'}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/nbinteract/pull_from_github.py", line 87, in pull_from_github
    _pull_and_resolve_conflicts(repo, branch_name, progress=progress)
  File "/opt/conda/lib/python3.5/site-packages/nbinteract/pull_from_github.py", line 249, in _pull_and_resolve_conflicts
    git_cli.merge('-Xours', 'origin/' + branch)
  File "/opt/conda/lib/python3.5/site-packages/git/cmd.py", line 425, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/git/cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/conda/lib/python3.5/site-packages/git/cmd.py", line 688, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git merge -Xours origin/master
  stdout: 'Updating 3c9dd51..66475d0'
  stderr: 'error: The following untracked working tree files would be overwritten by merge:
	session4/ASSIGNMENT-2-MAUP.ipynb
Please move or remove them before you can merge.
Aborting'
```

**Comment by SaladRaider** [comment]
Here was the error that prevented nbinteract from displaying the correct error message to the user:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/nbinteract/handlers.py", line 125, in open
    progress=Progress(username, self.write_message)
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.5/site-packages/nbinteract/pull_from_github.py", line 102, in pull_from_github
    util.logger.exception()
TypeError: exception() missing 1 required positional argument: 'msg'
```

**Comment by gunjanbaid** [comment]
@SaladRaider Sorry for the late reply, thanks so much for looking into this. I'll pass along the explanation to the connector instructors. 

Can you elaborate a bit more on the first solution (appending .untracked.<unique hash>)? Is there something special about this name format? Simply renaming files did not seem to work for the instructors.

Either of the solutions would be great to implement for the future!

For now, I may suggest just using different locations for interact link testing and assignment content testing.

**Comment by SaladRaider** [comment]
@gunjanbaid Yeah, that solution also works.

Hmm... that's strange. I was able to get it to work by renaming the files. I may be missing something, so I can try a couple more tests.

There isn't anything really that special about that naming convention. I just threw it out there as something that we can do so that there aren't file name conflicts with upstream.

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
