### ISSUE TITLE
Errors out when trying to pull and an existing folder with the same name as the repo exists

### ISSUE THREAD

**Issue by SaladRaider** [data-8/nbpuller#37]
### How to recreate the error:
1. Create a new folder in the root directory of the notebook tree called 'data8assets'
2. Create a new text file called whatever you want with some text inside. There should be nothing else in the folder.
3. Hit this link: http://datahub.berkeley.edu/user-redirect/interact?repo=data8assets&path=materials/sp17/lab/lab02

### The reason why nbpuller errors out:

It checks whether the directory already exists, if it does, nbpuller does not initialize the new repo. (pull_from_remote.py)
```
if not os.path.exists(repo_dir):
            _initialize_repo(
                ...
            )
```
In this case, the 'data8assets' folder already exists since we created it manually, so nbpuller does not initialize the data8assets repo for use. So, when nbpuller tries to assign the git repo that it expects already exists to an object here: `repo = git.Repo(repo_dir)`, it realizes that it is actually not a git repo and errors out.

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
