### ISSUE TITLE
Change the interact malformed html page to be generic

### ISSUE THREAD

**Issue by SaladRaider** [data-8/nbpuller#38]
Right now, the message specifically mentions Data8, and links to data8.org. However, it may not be used just only for the data8 class. Perhaps the extension can read from env variables to customize the title and the link.

<img width="764" alt="screen shot 2017-04-17 at 1 53 03 pm" src="https://cloud.githubusercontent.com/assets/13090194/25104436/3337ee5c-2375-11e7-9baa-001d4a512963.png">

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
