### ISSUE TITLE
Complete refactor into many different subcomponents

### ISSUE THREAD

**Issue by yuvipanda** [data-8/nbpuller#43]
I've been thinking about splitting this into varying subcomponents that would allow us to test them better, reduce the size of the code base, reduce complexity, and enable faster development.

I propose the following split:

1. gitautosync - A simple command line utility that when run, will synchronize a github repository with a local repository. It'll automatically deal with conflicts as we do now, and produce useful output to stdout. No dependencies on notebooks at all. This could (but need not be!) sparse if necessary - although ideally the git repos given to students would just be cleaned up instead.
2. nbperiodicrunner - A simple notebook extension that just runs a set of processes at a given time interval. We can use this to run gitautosync every few minutes in the background.

In addition, we can use a `postStart` lifecycle hook to perform a sync immediately when the notebook starts. This allows us to continue using URLs like we do now, except the git action is asynchronous, unrelated to the path that's being used, and also constantly happening.

We can easily just use a git mirror so we don't run into rate limit issues with GitHub.

I *think* this should cover all the use cases that we use nbpuller for right now at Berkeley, and would also enable its use in other areas more easily.

**Comment by SaladRaider** [comment]
@yuvipanda I see. Yeah, this makes sense. Do you want me to create new repos for each?

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
