### ISSUE TITLE
Production config has DEBUG=True

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbpuller#44]
This causes websockets to run over ws:// rather than wss:// which in turn prevents nbpuller from working on https://data8r.datahub.berkeley.edu.

It seems like DEBUG only affects this one thing.

**Comment by yuvipanda** [comment]
We should detect if we are being served over https and use that instead of
setting DEBUG

**Comment by ryanlovett** [comment]
Just sent a PR. :)

**Comment by SaladRaider** [comment]
I merged your PR, so I'm going to close this issue.
