### ISSUE TITLE
Does not work if account does not yet exist.

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbpuller#47]
If a user has never logged in and clicks an interact link, they will be directed to the Control Panel. After clicking "start my server" they will be directed to an empty file listing. A second visit to the interact link is required to clone all the materials.

**Comment by yuvipanda** [comment]
Hasn't this always been the case, because oauthenticator doesn't preserve
the url? Users don't need to start their server - they just need to be
already logged in.

**Comment by ryanlovett** [comment]
Yes but we didn't have an issue to track it.

**Comment by yuvipanda** [comment]
This repo is deprecated now! https://github.com/data-8/nbgitpuller is what is now going to be used.
