### ISSUE TITLE
Could step-by-step examples be documented please

### ISSUE THREAD

**Issue by rs2** [data-8/nbpuller#48]
E.g. when invoking

`http://localhost:8888/interact?repo=jupyter/dashboards&path=etc/notebooks/bokeh_demo/bokeh_demo.ipynb`

I get 

```
Cloning into 'jupyter/dashboards'...
remote: Not Found
```

**Comment by SaladRaider** [comment]
try adding '&account=jupyter' and change 'repo=jupyter/dashboards' to 'repo=dashboards'. i think that should work.

**Comment by rs2** [comment]
Tried that, but got `Status: Specified github account jupyter is not allowed.`
